// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlRQpK3JRmIRxIyZm3vSvvAcC8BYo4YDY',
    appId: '1:204647889968:web:db3527ff2521491ff341f5',
    messagingSenderId: '204647889968',
    projectId: 'basic-firebase-29c26',
    authDomain: 'basic-firebase-29c26.firebaseapp.com',
    databaseURL: 'https://basic-firebase-29c26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basic-firebase-29c26.appspot.com',
    measurementId: 'G-MMMWKDFEH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOf0pHUiOOZ73oksJ9fpQnu3idyId6uUU',
    appId: '1:204647889968:android:c4446ded3f752de3f341f5',
    messagingSenderId: '204647889968',
    projectId: 'basic-firebase-29c26',
    databaseURL: 'https://basic-firebase-29c26-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basic-firebase-29c26.appspot.com',
  );
}
